# Generated by Django 3.2.16 on 2023-01-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230118_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
