# Generated by Django 3.2.16 on 2023-01-19 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_director_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BlogUser',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='MoviePost',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Reviews',
        ),
    ]
