# Generated by Django 3.2.16 on 2023-01-19 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20230119_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='MoviePost',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='BlogUser',
            new_name='User',
        ),
    ]
