# Generated by Django 3.2.16 on 2023-01-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230120_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='director_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to='blog.moviegenre'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='genre_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
