# Generated by Django 3.2.16 on 2023-01-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230122_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
