# Generated by Django 3.2.16 on 2023-01-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_director_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='genre',
        ),
        migrations.AddField(
            model_name='director',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='director', to='blog.MovieGenre'),
        ),
    ]
