# Generated by Django 3.2.16 on 2023-01-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20230128_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='director', to='blog.MovieGenre'),
        ),
    ]
