# Generated by Django 3.2.16 on 2023-01-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_director_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegenre',
            name='age_rating',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
