# Generated by Django 3.2.16 on 2023-01-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_userrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='request',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='genre',
            field=models.ManyToManyField(blank=True, to='blog.MovieGenre'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='director_name',
            field=models.CharField(max_length=50),
        ),
    ]
