# Generated by Django 3.2.16 on 2023-02-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20230131_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='bio',
            new_name='request',
        ),
    ]
