# Generated by Django 3.2.16 on 2023-02-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_rename_bio_userrequest_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='request_status',
            new_name='approved',
        ),
    ]
