# Generated by Django 3.2.16 on 2023-02-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_userrequest_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='author',
        ),
    ]
